services:
  - postgresql
 notifications:
    slack: andela:eROs9w0H9iaQ7D2XC9jl4d5W

before_script:
  - psql -c 'create database bucketlist_test;' -U postgres
language: python
python:


  - "3.6"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script: python manage.py cov
after_success:
  coveralls
