services:
  - postgresql

before_script:
  - psql -c 'create database bucketlist_test;' -U postgres
language: python
python:


  - "3.6"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script: nosetests --cover-package=bucketlist --with-coverage
after_success:
  coveralls

notifications:
    slack: andela:7AgcICydnCCaIALOas7uMHuR
